version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: taskapp-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - taskapp-net

  backend:
    build: ./backend
    container_name: taskapp-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskapp
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - taskapp-net

  frontend:
    build: ./frontend
    container_name: taskapp-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - taskapp-net

volumes:
  mongo_data:

networks:
  taskapp-net:
    driver: bridge
